#!/usr/bin/env python3

from curl_cffi import requests
from Details.Cookie import *
from Details.Products import GetCategories, GetProducts
from Details.Database import UpdateData
from Details.AI import Analyse

import sys
import os

def RequestCookie(cookie_path: str) -> dict:
  print('Enter the cookie:')
  cookie_str = input()
  SaveCookie(cookie_path, cookie_str)
  return ParseCookie(cookie_str)


DEFAULT_PROMT = 'Топ-20 продуктов для ужина и полдника, полезных при высоких умственных нагрузках, желательно поменьше сахара и недорогих, которые не нужно готовить, не напитков'

def main():
  cookie_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'Details', 'Cookie')

  if len(sys.argv) > 2:
    print("Invalid argument count.")
    sys.exit(-1)

  healthy = False
  if len(sys.argv) == 2:
    if sys.argv[1] not in ('--update-cookie', '-u', '--healthy', '-h'):
      print("Unknown flag.")
      sys.exit(-1)
    if sys.argv[1] in ('--update-cookie', '-u'):
      cookies = RequestCookie(cookie_path)
    else:
      healthy = True

  if os.path.getsize(cookie_path) == 0:
    cookies = RequestCookie(cookie_path)
  else:
    cookies = ReadCookie(cookie_path)

  with requests.Session(cookies=cookies, impersonate='chrome136') as session:
    products = GetProducts(session, GetCategories(session, healthy))
    print('Received', len(products), 'products')
    collected = UpdateData(session, products)

    print('\nCustom promt:')
    promt = input()
    if len(promt) == 0:
      print('Default promt will be used')
      promt = DEFAULT_PROMT

    print(Analyse(promt, collected))
    
  
if __name__ == '__main__':
  main()
