#!/usr/bin/env python3

from Details.SQLCode import DATABASE_PATH, CREATE_DATABASE
from contextlib import closing

import os
import platform
import sqlite3


def Update(rc_path: str, rc_name: str) -> bool:
  with open(rc_path, 'a+') as rc:
    rc.seek(0)
    app_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'app')
    add_exec = f"export PATH=\"{app_path}:$PATH\""
    
    if add_exec not in rc.read():
      rc.write('\n' + add_exec + '\n')
      print(f"{rc_name} has been updated")
      return True

  return False


def main():
  with closing(sqlite3.connect(DATABASE_PATH)) as database:
    database.executescript(CREATE_DATABASE)

  home = os.path.expanduser('~')
  shell = os.path.basename(os.environ.get('SHELL', ''))
  is_mac = platform.system() == 'Darwin'

  rc_candidates = [
    ('.bashrc', shell == 'bash' and not is_mac),
    ('.bash_profile', shell == 'bash' and is_mac),
    ('.zshrc', shell == 'zsh'),
  ]

  updated = False

  for rc_name, update_required in rc_candidates:
    rc_path = os.path.join(home, rc_name)

    if os.path.isfile(rc_path) or update_required:
      updated = Update(rc_path, rc_name) or updated

  if not updated:
    print(f"Nothing to update, shell: {shell or 'unknown'}")
  else:
    print("OK")


if __name__ == '__main__':
  main()
